DB_NAME = "db.sqlite3"

IMAP_HOSTNAME = ""
IMAP_USERNAME = ""
IMAP_PASSWORD = ""
IMAP_MAILBOX = "Junk"
MAIL_TIMEOUT = "30" # In days

TELEGRAM_BOT_TOKEN = ""
TELEGRAM_INFO_CHAT_ID = 0
TELEGRAM_NOTIFS_CHAT_ID = 0
